### ISSUE TITLE
Out of memory on completion

### ISSUE THREAD

**Issue by TheWebranger** [ffuf/ffuf#386]
Hi @joohoi,
First of all thanks for this amazing tool.

fuff is working fine during fuzzing but running into 'out of memory' issue after completion, probably while writing output to file:

```
:: Progress: [900000/900000] :: Job [1/1] :: 113 req/sec :: Duration: [2:01:47] :: Errors: 7 ::
fatal error: runtime: out of memory
```

Parts of stacktrace:

```
...
runtime stack:                                                                                                                      
runtime.throw(0x851e77, 0x16)                                                                                                       
        go/src/runtime/panic.go:1116 +0x72                                                                                          
runtime.sysMap(0xc050000000, 0x8000000, 0xb24b58)                                                                                   
        go/src/runtime/mem_linux.go:169 +0xc6                                                                                       
runtime.(*mheap).sysAlloc(0xb09b00, 0x6c00000, 0x42bb17, 0xb09b08)                                                                  
        go/src/runtime/malloc.go:727 +0x1e5                                                                                         
runtime.(*mheap).grow(0xb09b00, 0x34eb, 0x0)                                                                                        
        go/src/runtime/mheap.go:1344 +0x85    
...
goroutine 1 [running]:                                                                                                              
runtime.systemstack_switch()                                                                                                        
        go/src/runtime/asm_amd64.s:330 fp=0xc000408970 sp=0xc000408968 pc=0x468de0                                                  
runtime.mallocgc(0x69d6000, 0x82eaa0, 0x6fc0e9a413ac3001, 0xffffffffffffffff)                                                       
        go/src/runtime/malloc.go:1070 +0x938 fp=0xc000408a10 sp=0xc000408970 pc=0x40db38
runtime.growslice(0x82eaa0, 0xc0494e8000, 0xc1849, 0xc1849, 0xc184a, 0xc0494e8000, 0x9acdb, 0xc1849)
        go/src/runtime/slice.go:230 +0x1e9 fp=0xc000408a78 sp=0xc000408a10 pc=0x44c889
github.com/ffuf/ffuf/pkg/output.writeJSON(0xc0000c8000, 0xc02aa24000, 0xdbb2f, 0x108980, 0xc0221c2bd0, 0xdbba0)
        src/github.com/ffuf/ffuf/pkg/output/file_json.go:70 +0x68b fp=0xc000408d98 sp=0xc000408a78 pc=0x78c32b
github.com/ffuf/ffuf/pkg/output.(*Stdoutput).Finalize(0xc00000cac0, 0x24c0cab, 0xaf1b60)
        src/github.com/ffuf/ffuf/pkg/output/stdout.go:263 +0x2f2 fp=0xc000408df8 sp=0xc000408d98 pc=0x790232
github.com/ffuf/ffuf/pkg/ffuf.(*Job).Start(0xc000088100)
        src/github.com/ffuf/ffuf/pkg/ffuf/job.go:122 +0x3cf fp=0xc000408e98 sp=0xc000408df8 pc=0x73256f
...
```

I have observed that ffuf writes output at the end of the task. Is it possible to flush the output (write output to file at runtime)?

**Comment by bsysop** [comment]
Hi @TheWebranger,

Looks you are `out of memory`

Could you give details about the VPS you are using please?

Thanks

**Comment by TheWebranger** [comment]
Hi @bsysop,
I am testing it on 1GB instances as part of 'distributed fuzzing'. It's working pretty well but fails only in the end while writing output to file.

**Comment by bsysop** [comment]
@TheWebranger got it, I was thinking exactly in that,

Look, we don't have minimum requirements for FFUF yet, but depending the wordlist, the targets, the quantity of results founds, etc, I can't tell you that 1GB depending what you are doing is very low, when I need do something distributed, I use 2GB Vps and normally works nice, depending what you need, FFUF could use several GB's of memory.

What I have seen is: FFUF is extremely fast, but... sometimes he need more time to process and write that at the end of the process (sometimes hours after finished the HTTP Requests...)

I don't think debugging and improve this was in the road map yet.

Tag joohoi, if you want a deeper answer here :), but don't expect like a solution..

What I did is: SPLIT the jobs by parts.

100.000 targets / 10 = 10 files with 10.000 targets each.

**Comment by TheWebranger** [comment]
Thanks for the reponse @bsysop

**Comment by bsysop** [comment]
You are welcome @TheWebranger
Happy hacking!
