### ISSUE TITLE
Crashes on invalid argument to rate interactive command

### ISSUE THREAD

**Issue by ben-elttam** [ffuf/ffuf#740]
If you pass a non-positive integer to the `rate` interactive command it will panic.

# Reproduction Steps

With Fuzz Faster U Fool - v2.1.0:

1. Start a scan
2. Press ENTER to enter interactive mode
3. Run `rate 0` -- it will crash (panic)

# Logs

```
:: Progress: [68002/1092120] :: Job [1/1] :: 0 req/sec :: Duration: [1:48:37] :: Errors: 67961 ::
[INFO] ------ PAUSING ------

entering interactive mode
type "help" for a list of commands, or ENTER to resume.
> help

available commands:
 afc  [value]             - append to status code filter
 fc   [value]             - (re)configure status code filter
 afl  [value]             - append to line count filter
 fl   [value]             - (re)configure line count filter
 afw  [value]             - append to word count filter
 fw   [value]             - (re)configure word count filter
 afs  [value]             - append to size filter
 fs   [value]             - (re)configure size filter
 aft  [value]             - append to time filter
 ft   [value]             - (re)configure time filter
 rate [value]             - adjust rate of requests per second (active: 10)
 queueshow                - show job queue
 queuedel [number]        - delete a job in the queue
 queueskip                - advance to the next queued job
 restart                  - restart and resume the current ffuf job
 resume                   - resume current ffuf job (or: ENTER)
 show                     - show results for the current job
 savejson [filename]      - save current matches to a file
 help                     - you are looking at it
> rate
[ERR] Please define the new rate
> rate 0
panic: non-positive interval for NewTicker

goroutine 18 [running]:
time.NewTicker(0x907290?)
        $GOROOT/src/time/tick.go:22 +0xe5
github.com/ffuf/ffuf/v2/pkg/ffuf.(*RateThrottle).ChangeRate(0xc0056bba3b?, 0x0)
        /home/joona/GolandProjects/ffuf/pkg/ffuf/rate.go:75 +0x67
github.com/ffuf/ffuf/v2/pkg/interactive.(*interactive).handleInput(0xc000467eb8, {0xc000074047?, 0x0?, 0x0?})
        /home/joona/GolandProjects/ffuf/pkg/interactive/termhandler.go:190 +0xa05
github.com/ffuf/ffuf/v2/pkg/interactive.Handle(0x0?)
        /home/joona/GolandProjects/ffuf/pkg/interactive/termhandler.go:28 +0xfc
main.main.func1()
        /home/joona/GolandProjects/ffuf/main.go:259 +0x1b
created by main.main in goroutine 1
        /home/joona/GolandProjects/ffuf/main.go:258 +0xa3b
```

Earlier when I ran `help` I saw:

```
 rate [value]             - adjust rate of requests per second (active: 0)
```

I ran `rate 10`, and then later I ran `rate 0` shown above, thinking `0` was the default and meant no limit.

This was 1h48m and only 68k into a 1M run, but it's still painful due to the lack of being able to resume #513.

**Comment by joohoi** [comment]
Thanks for reporting this. It should now be fixed.
